id: I1AAA8C47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T08:38:40+00:00'
last_modified: '2022-06-08T16:51:31.297817+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19997
  title: མདོ་ཆེན་ཨ་ཁོ་རིས་ཐུབ་བསྟན་ཉི་ཤར་གླིང་གི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    472F:
      image_group_id: I2PD20007
      title: ''
      total_pages: 494
      order: 1
      base_file: 472F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
