id: P010694
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19997
  title: མདོ་ཆེན་ཨ་ཁོ་རིས་ཐུབ་བསྟན་ཉི་ཤར་གླིང་གི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    4403a50b71e54156a8338d3735e5e4b1:
      image_group_id: I2PD20007
      title: ''
      volume_number: 1
      total_pages: 494
      base_file: v001.txt
